// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pantry.Data;

namespace Pantry.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20201111003122_DSED06Migration")]
    partial class DSED06Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pantry.Models.Categories", b =>
                {
                    b.Property<Guid>("CategoriesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriesID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Pantry.Models.PantryItems", b =>
                {
                    b.Property<Guid>("PantryItemsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PantryItemsID");

                    b.HasIndex("CategoriesID");

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("Pantry.Models.PantryItems_Stock", b =>
                {
                    b.Property<Guid>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateBought")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PantryItemsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("StockID");

                    b.HasIndex("PantryItemsID");

                    b.ToTable("PantryItems_Stock");
                });

            modelBuilder.Entity("Pantry.Models.PantryItems", b =>
                {
                    b.HasOne("Pantry.Models.Categories", "Categories")
                        .WithMany("PantryItems")
                        .HasForeignKey("CategoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pantry.Models.PantryItems_Stock", b =>
                {
                    b.HasOne("Pantry.Models.PantryItems", "PantryItems")
                        .WithMany("PantryItems_Stock")
                        .HasForeignKey("PantryItemsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            
#pragma warning restore 612, 618
        }
    }
}
